languageCode = "zh-cn"
title = "Paper"
theme = "hugo-theme-paper"
baseURL = "http://localhost"
themesDir = "../.."
Paginate = 10
summaryLength = 20
googleAnalytics = ""
disqusShortname = ""

[params]
  headerHtml = '<script>console.log("headerHtml");</script>'